Repository goatshriek/stumpless, pull requests merged in 2022-10, with the labels that each got.

#250 improve localization
  .github/workflows/analysis.yml
  docs/localization.md
  include/private/config/locale/bg-bg.h
  include/private/config/locale/cz-cz.h
  include/private/config/locale/de-de.h
  include/private/config/locale/el-gr.h
  include/private/config/locale/en-us.h
  include/private/config/locale/es-es.h
  include/private/config/locale/fr-fr.h
  include/private/config/locale/it-it.h
  include/private/config/locale/pl-pl.h
  include/private/config/locale/sk-sk.h
  include/private/config/locale/sv-se.h
  l10n/ko-kr/README.md
  l10n/ko-kr/docs/CODE_OF_CONDUCT.md
  l10n/zh-cn/README.md
  l10n/zh-cn/docs/CODE_OF_CONDUCT.md
  scripts/add_l10n_string.rb
  scripts/check_l10n.rb
Labels: l10n

#255 document disallowed change types
  docs/CONTRIBUTING.md
Labels: documentation

#260 avoid SIGPIPE termination
  ChangeLog.md
  docs/roadmap.md
  src/config/have_sys_socket.c
  test/function/target/tcp4.cpp
  test/function/target/tcp6.cpp
  tools/check_headers/standard_library.yml
Labels: bug

#266 updated Spanish localization
  include/private/config/locale/es-es.h
Labels: l10n

#277 fix element name length race
  src/element.c
Labels: bug

#280 Add a local language: zh-CN
  .github/workflows/locale.yml
  CMakeLists.txt
  README.md
  include/private/config/locale/wrapper.h
  include/private/config/locale/zh-cn.h
Labels: l10n

#285 Adding Hindi for localisation
  .github/workflows/locale.yml
  CMakeLists.txt
  README.md
  include/private/config.h.in
  include/private/config/locale/hi-in.h
  include/private/config/locale/wrapper.h
Labels: l10n

#291 Added Bengali (bn-in) for Localization
  .github/workflows/locale.yml
  CMakeLists.txt
  include/private/config.h.in
  include/private/config/locale/bn-in.h
  include/private/config/locale/wrapper.h
Labels: l10n

#296 Fixes #295: factor config_get_now out of wrapper.h
  include/private/config/wrapper.h
  include/private/config/wrapper/get_now.h
  src/formatter.c
  src/target/journald.c
  tools/check_headers/stumpless.yml
  tools/check_headers/stumpless_private.yml
Labels: refactor
