Repository goatshriek/stumpless, pull requests merged in 2024-10, with the labels that each got.

#461 Documentation for memory.h (#371)
  include/private/memory.h
Labels: documentation

#462 Translation of all german messages (#117)
  include/private/config/locale/de-de.h
Labels: l10n

#463 Readme Korean localization (|10n/ko-k0r/README.md)
  l10n/ko-kr/README.md
  l10n/ko-kr/자원/로고와이름.svg
Labels: l10n

#464 test cache page allocation failure
  src/cache.c
  test/function/entry.cpp
Labels: testing
