Repository goatshriek/stumpless, pull requests merged in 2024-07, with the labels that each got.

#429 merge priority and prival files
  CITATION.cff
  CMakeLists.txt
  ChangeLog.md
  include/private/entry.h
  include/private/prival.h
  include/stumpless.h
  include/stumpless/priority.h
  include/stumpless/prival.h
  src/entry.c
  src/priority.c
  src/prival.c
  src/target.c
  test/function/priority.cpp
  test/function/prival.cpp
  test/performance/prival.cpp
  tools/check_headers/stumpless.yml
  tools/check_headers/stumpless_private.yml
  tools/cmake/install_headers.cmake
Labels: refactor

#427 Terminal ansi colors
  include/private/target/stream.h
  include/stumpless/severity.h
  include/stumpless/target/stream.h
  src/target.c
  src/target/stream.c
  src/windows/stumpless.def
  test/function/target/stream.cpp
Labels: enhancement

#430 fix l10n script
  include/private/config/locale/bg-bg.h
  include/private/config/locale/bn-in.h
  include/private/config/locale/cz-cz.h
  include/private/config/locale/da-dk.h
  include/private/config/locale/de-de.h
  include/private/config/locale/el-gr.h
  include/private/config/locale/en-us.h
  include/private/config/locale/es-es.h
  include/private/config/locale/fr-fr.h
  include/private/config/locale/he-il.h
  include/private/config/locale/hi-in.h
  include/private/config/locale/hu-hu.h
  include/private/config/locale/it-it.h
  include/private/config/locale/ja-jp.h
  include/private/config/locale/ko-kr.h
  include/private/config/locale/pl-pl.h
  include/private/config/locale/pt-br.h
  include/private/config/locale/si-lk.h
  include/private/config/locale/sk-sk.h
  include/private/config/locale/sq-al.h
  include/private/config/locale/sv-se.h
  include/private/config/locale/sw-ke.h
  include/private/config/locale/te-in.h
  include/private/config/locale/tr-tr.h
  include/private/config/locale/zh-cn.h
  scripts/add_l10n_string.rb
  src/target/stream.c
Labels: bug, l10n

#432 add benchmark for stumpless_get_prival_string
  test/performance/prival.cpp
Labels: enhancement, testing
