Repository goatshriek/stumpless, pull requests merged in 2025-06, with the labels that each got.

#505 feat: Add facility function tests and fix missing test targets
  include/stumpless/facility.h
  src/facility.c
  test/function/facility.cpp
Labels: enhancement

#506 feat: added test for non cache owned memory fallback, refactored cache_free
  src/cache.c
  test/function/entry.cpp
Labels: testing, refactor

#507 Frenchlocaleupdates
  README.md
  l10n/fr-fr/INSTALL.md
  l10n/fr-fr/README.md
  l10n/fr-fr/actifs/logo.svg
  l10n/fr-fr/docs/CODE_OF_CONDUCT.md
  l10n/fr-fr/docs/CONTRIBUTING.md
  l10n/fr-fr/docs/SECURITY.md
  l10n/fr-fr/docs/dependencies.md
  l10n/fr-fr/docs/development.md
  l10n/fr-fr/docs/portability.md
  l10n/fr-fr/docs/style.md
  l10n/fr-fr/docs/thread_safety.md
  l10n/fr-fr/docs/vision.md
Labels: l10n
