Repository goatshriek/stumpless, pull requests merged in 2025-05, with the labels that each got.

#499 refactor cmake scripts
  .github/workflows/cygwin.yml
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  ChangeLog.md
  INSTALL.md
  docs/dependencies.md
  docs/development.md
  tools/cmake/add_found_library.cmake
  tools/cmake/benchmark.cmake
  tools/cmake/chain.cmake
  tools/cmake/config_files.cmake
  tools/cmake/cpp.cmake
  tools/cmake/cpp_test.cmake
  tools/cmake/examples.cmake
  tools/cmake/function_tests.cmake
  tools/cmake/fuzz_tests.cmake
  tools/cmake/google_libs.cmake
  tools/cmake/gtest.cmake
  tools/cmake/journald.cmake
  tools/cmake/network.cmake
  tools/cmake/options.cmake
  tools/cmake/performance_tests.cmake
  tools/cmake/single_file.cmake
  tools/cmake/socket.cmake
  tools/cmake/sqlite3.cmake
  tools/cmake/test.cmake
  tools/cmake/thread_safety_tests.cmake
  tools/cmake/wel.cmake
  tools/pkg-config/libstumpless.pc.in
  tools/portage/libstumpless.ebuild.in
Labels: refactor

#502 korean translate for two defines
  include/private/config/locale/ko-kr.h
Labels: l10n

#501 #448 - Added stumpless_entry_to_string and test cases for output format and empty fields
  include/stumpless/entry.h
  src/entry.c
  src/windows/stumpless.def
  test/function/entry.cpp
  tools/check_headers/stumpless.yml
Labels: enhancement
