Repository goatshriek/stumpless, pull requests merged in 2025-08, with the labels that each got.

#510 docs(memory): add Doxygen comments for alloc_array and realloc_array
  include/private/memory.h
Labels: documentation

#519 expand size of buffer in broken target test
  test/function/target.cpp
Labels: bug

#518 Add Polish translation
  include/private/config/locale/pl-pl.h
Labels: l10n

#521 docs(private): add Doxygen for error.h
  include/private/error.h
Labels: documentation
